package com.retro.vhs.vhs

/** What the character generator burns into the picture. */
enum class OsdStyle { NONE, CAMCORDER, DATE_ONLY, PLAYER, TRACKING, NEWS, SECURITY }

/**
 * Audio path of the machine. Linear VHS audio was a mono edge track running at tape
 * speed, so it lost the top octave and wobbled; Hi-Fi AFM (Video8/Hi8/S-VHS) was
 * genuinely good but hissed on a worn tape.
 */
data class AudioProfile(
    val lowCutHz: Float,
    val highCutHz: Float,
    val hiss: Float,
    val wowRateHz: Float,
    val wowDepth: Float,
    val flutterRateHz: Float,
    val flutterDepth: Float,
    val drive: Float,
    val mono: Boolean,
    val dropouts: Float = 0f
) {
    companion object {
        val LINEAR_SP = AudioProfile(90f, 10000f, 0.010f, 0.7f, 0.0022f, 6.3f, 0.0010f, 1.5f, true)
        val LINEAR_EP = AudioProfile(120f, 6200f, 0.026f, 0.6f, 0.0050f, 5.4f, 0.0026f, 2.1f, true, 0.05f)
        val BETA_MONO = AudioProfile(80f, 11000f, 0.008f, 0.8f, 0.0018f, 7.1f, 0.0009f, 1.4f, true)
        val HIFI_AFM = AudioProfile(45f, 15000f, 0.0025f, 0.4f, 0.0006f, 8.0f, 0.0004f, 1.15f, false)
        val ENG_FIELD = AudioProfile(110f, 9000f, 0.014f, 0.5f, 0.0016f, 6.0f, 0.0008f, 1.7f, true)
        val WORN = AudioProfile(140f, 5200f, 0.038f, 0.9f, 0.0075f, 4.6f, 0.0040f, 2.4f, true, 0.14f)
        val CLEAN = AudioProfile(60f, 14000f, 0.0015f, 0.3f, 0.0004f, 8.0f, 0.0002f, 1.05f, false)
    }
}

/**
 * One machine + one tape + one television, fully described. Defaults are a mid-80s
 * consumer VHS deck, so each preset only states what makes it different.
 */
data class VhsPreset(
    val id: String,
    val name: String,
    val year: String,
    val format: String,
    val blurb: String,

    // --- stage 1: lens and pickup ---
    val exposure: Float = 1.02f,
    val gamma: Float = 1.0f,
    val contrast: Float = 1.05f,
    val saturation: Float = 1.0f,
    val tintR: Float = 1.0f,
    val tintG: Float = 1.0f,
    val tintB: Float = 1.0f,
    val softness: Float = 0.35f,
    val ccdSmear: Float = 0.0f,
    val tubeLag: Float = 0.0f,
    val lensBloom: Float = 0.22f,
    val lensVignette: Float = 0.18f,

    // --- stage 2: composite + tape ---
    val lumaBw: Float = 3.0f,
    val chromaBw: Float = 26f,
    val chromaDelay: Float = 3.0f,
    val sharpen: Float = 0.55f,
    val dotCrawl: Float = 0.50f,
    val rainbow: Float = 0.25f,
    val noise: Float = 0.045f,
    val noiseDark: Float = 1.2f,
    val chromaNoise: Float = 0.020f,
    val jitter: Float = 0.9f,
    val warp: Float = 1.2f,
    val headSwitch: Float = 0.85f,
    val tracking: Float = 0.0f,
    val dropout: Float = 0.02f,
    val ghost: Float = 0.0f,
    val ghostDist: Float = 0.010f,
    val interlace: Float = 0.9f,
    val persist: Float = 0.10f,
    val sat: Float = 1.0f,
    val hue: Float = 0.0f,
    val black: Float = 0.06f,
    val whiteClip: Float = 0.98f,
    val snow: Float = 0.0f,

    // --- stage 3: display ---
    val curve: Float = 0.035f,
    val scanline: Float = 0.45f,
    val mask: Float = 0.18f,
    val crtBloom: Float = 0.35f,
    val crtVignette: Float = 0.30f,
    val glare: Float = 0.10f,
    val overscan: Float = 0.03f,
    val bright: Float = 1.03f,
    val gammaOut: Float = 1.0f,
    val flicker: Float = 0.15f,
    val corner: Float = 0.02f,

    // --- machine furniture ---
    val osd: OsdStyle = OsdStyle.CAMCORDER,
    val osdColor: Int = 0xFFFFFFFF.toInt(),
    val tapeSpeed: String = "SP",
    val audio: AudioProfile = AudioProfile.LINEAR_SP
) {
    companion object {

        val ALL: List<VhsPreset> = listOf(

            VhsPreset(
                id = "vhs_sp",
                name = "VHS SP",
                year = "1983",
                format = "VHS · Standard Play",
                blurb = "The reference tape. 240 lines of luma, colour smeared sideways, honest dot crawl.",
                osd = OsdStyle.CAMCORDER,
                audio = AudioProfile.LINEAR_SP
            ),

            VhsPreset(
                id = "vhs_ep",
                name = "VHS EP",
                year = "1987",
                format = "VHS · Extended Play (6 hr)",
                blurb = "Six hours on one T-120. A third of the tape speed, and it shows in everything.",
                softness = 0.45f,
                lumaBw = 6.0f,
                chromaBw = 46f,
                chromaDelay = 5.0f,
                sharpen = 0.42f,
                dotCrawl = 0.55f,
                rainbow = 0.32f,
                noise = 0.105f,
                noiseDark = 1.7f,
                chromaNoise = 0.045f,
                jitter = 2.3f,
                warp = 3.6f,
                dropout = 0.09f,
                interlace = 0.95f,
                sat = 0.82f,
                black = 0.13f,
                whiteClip = 0.955f,
                snow = 0.10f,
                scanline = 0.5f,
                crtBloom = 0.45f,
                osd = OsdStyle.PLAYER,
                tapeSpeed = "EP",
                audio = AudioProfile.LINEAR_EP
            ),

            VhsPreset(
                id = "betamax",
                name = "Betamax",
                year = "1982",
                format = "Betamax · Beta II",
                blurb = "Sony's better picture that lost the war. Tighter luma, warmer, steadier transport.",
                tintR = 1.04f,
                tintG = 1.0f,
                tintB = 0.95f,
                lumaBw = 2.5f,
                chromaBw = 22f,
                chromaDelay = 2.4f,
                sharpen = 0.5f,
                dotCrawl = 0.42f,
                rainbow = 0.22f,
                noise = 0.040f,
                chromaNoise = 0.016f,
                jitter = 0.6f,
                warp = 0.9f,
                headSwitch = 0.7f,
                hue = 0.035f,
                sat = 1.06f,
                scanline = 0.42f,
                osd = OsdStyle.PLAYER,
                tapeSpeed = "β II",
                audio = AudioProfile.BETA_MONO
            ),

            VhsPreset(
                id = "vhsc_cam",
                name = "VHS-C Cam",
                year = "1985",
                format = "VHS-C · Palmcorder",
                blurb = "Compact camcorder with a single chip CCD. Smears on every highlight, dates every frame.",
                exposure = 1.06f,
                contrast = 1.12f,
                saturation = 0.96f,
                softness = 0.5f,
                ccdSmear = 0.85f,
                lensBloom = 0.4f,
                lensVignette = 0.32f,
                lumaBw = 3.4f,
                chromaBw = 30f,
                sharpen = 0.62f,
                noise = 0.070f,
                noiseDark = 1.6f,
                chromaNoise = 0.028f,
                jitter = 1.3f,
                warp = 1.8f,
                interlace = 1.0f,
                black = 0.09f,
                whiteClip = 0.965f,
                scanline = 0.38f,
                mask = 0.14f,
                crtBloom = 0.42f,
                glare = 0.14f,
                osd = OsdStyle.CAMCORDER,
                osdColor = 0xFFFFF2C0.toInt(),
                audio = AudioProfile.LINEAR_SP
            ),

            VhsPreset(
                id = "video8",
                name = "Video8",
                year = "1987",
                format = "Video8 · 8mm metal tape",
                blurb = "Metal particle tape in a Handycam. Cleaner, cooler, and the first one that sounded good.",
                tintR = 0.97f,
                tintG = 1.0f,
                tintB = 1.05f,
                softness = 0.3f,
                ccdSmear = 0.55f,
                lumaBw = 2.4f,
                chromaBw = 20f,
                chromaDelay = 2.2f,
                sharpen = 0.58f,
                dotCrawl = 0.34f,
                rainbow = 0.18f,
                noise = 0.033f,
                chromaNoise = 0.013f,
                jitter = 0.55f,
                warp = 0.8f,
                headSwitch = 0.55f,
                dropout = 0.012f,
                sat = 1.02f,
                black = 0.05f,
                scanline = 0.4f,
                mask = 0.16f,
                osd = OsdStyle.CAMCORDER,
                osdColor = 0xFFDDF4FF.toInt(),
                audio = AudioProfile.HIFI_AFM
            ),

            VhsPreset(
                id = "hi8",
                name = "Hi8",
                year = "1989",
                format = "Hi8 · S-video out",
                blurb = "End of the decade prosumer. 400 lines, S-video, so no dot crawl at all.",
                softness = 0.2f,
                ccdSmear = 0.45f,
                lensBloom = 0.18f,
                lensVignette = 0.14f,
                lumaBw = 1.5f,
                chromaBw = 15f,
                chromaDelay = 1.6f,
                sharpen = 0.68f,
                dotCrawl = 0.0f,
                rainbow = 0.0f,
                noise = 0.024f,
                noiseDark = 0.9f,
                chromaNoise = 0.008f,
                jitter = 0.35f,
                warp = 0.5f,
                headSwitch = 0.45f,
                dropout = 0.008f,
                persist = 0.06f,
                black = 0.04f,
                whiteClip = 0.99f,
                curve = 0.025f,
                scanline = 0.34f,
                mask = 0.12f,
                crtBloom = 0.25f,
                crtVignette = 0.22f,
                flicker = 0.10f,
                osd = OsdStyle.CAMCORDER,
                osdColor = 0xFFE8FFF0.toInt(),
                audio = AudioProfile.HIFI_AFM
            ),

            VhsPreset(
                id = "svhs",
                name = "S-VHS",
                year = "1988",
                format = "S-VHS · separated Y/C",
                blurb = "Super VHS with the luma kept apart from the chroma. Sharp, ringy, still tape.",
                softness = 0.22f,
                lumaBw = 1.4f,
                chromaBw = 18f,
                chromaDelay = 1.8f,
                sharpen = 0.85f,
                dotCrawl = 0.0f,
                rainbow = 0.0f,
                noise = 0.030f,
                chromaNoise = 0.011f,
                jitter = 0.5f,
                warp = 0.7f,
                headSwitch = 0.6f,
                black = 0.05f,
                curve = 0.03f,
                scanline = 0.4f,
                mask = 0.15f,
                osd = OsdStyle.PLAYER,
                tapeSpeed = "S-SP",
                audio = AudioProfile.HIFI_AFM
            ),

            VhsPreset(
                id = "umatic",
                name = "U-matic",
                year = "1980",
                format = "U-matic · 3/4\" · tube camera",
                blurb = "Local news on a shoulder rig, shot on a pickup tube: highlights bloom and drag comet trails.",
                exposure = 1.0f,
                contrast = 1.06f,
                saturation = 0.9f,
                tintR = 0.97f,
                tintG = 1.0f,
                tintB = 1.05f,
                softness = 0.52f,
                tubeLag = 0.55f,
                lensBloom = 0.48f,
                lensVignette = 0.32f,
                lumaBw = 2.7f,
                chromaBw = 24f,
                sharpen = 0.5f,
                dotCrawl = 0.45f,
                rainbow = 0.2f,
                noise = 0.062f,
                noiseDark = 1.5f,
                chromaNoise = 0.022f,
                jitter = 0.8f,
                warp = 1.4f,
                headSwitch = 0.5f,
                persist = 0.28f,
                black = 0.10f,
                whiteClip = 0.96f,
                curve = 0.06f,
                scanline = 0.6f,
                mask = 0.26f,
                crtBloom = 0.5f,
                crtVignette = 0.42f,
                glare = 0.22f,
                overscan = 0.05f,
                bright = 1.06f,
                flicker = 0.22f,
                corner = 0.028f,
                osd = OsdStyle.NEWS,
                osdColor = 0xFFFFFFFF.toInt(),
                audio = AudioProfile.ENG_FIELD
            ),

            VhsPreset(
                id = "tracking",
                name = "Tracking",
                year = "1986",
                format = "VHS · misaligned heads",
                blurb = "Nobody adjusted the tracking dial. Noise bands crawl up the picture and colour drops out.",
                softness = 0.42f,
                lumaBw = 5.0f,
                chromaBw = 40f,
                chromaDelay = 4.5f,
                sharpen = 0.5f,
                dotCrawl = 0.55f,
                rainbow = 0.35f,
                noise = 0.125f,
                noiseDark = 1.8f,
                chromaNoise = 0.055f,
                jitter = 3.1f,
                warp = 5.5f,
                headSwitch = 1.0f,
                tracking = 1.0f,
                dropout = 0.20f,
                interlace = 1.0f,
                sat = 0.62f,
                hue = -0.08f,
                black = 0.16f,
                whiteClip = 0.95f,
                snow = 0.34f,
                scanline = 0.5f,
                crtBloom = 0.45f,
                glare = 0.16f,
                flicker = 0.35f,
                osd = OsdStyle.TRACKING,
                tapeSpeed = "EP",
                audio = AudioProfile.WORN
            ),

            VhsPreset(
                id = "third_gen",
                name = "3rd Gen",
                year = "1989",
                format = "VHS · copy of a copy of a copy",
                blurb = "Duplicated deck to deck over an RF lead. Ghosted, washed out, ringing on every edge.",
                contrast = 0.98f,
                saturation = 0.9f,
                softness = 0.5f,
                lumaBw = 7.0f,
                chromaBw = 52f,
                chromaDelay = 6.0f,
                sharpen = 0.95f,
                dotCrawl = 0.7f,
                rainbow = 0.45f,
                noise = 0.098f,
                noiseDark = 1.9f,
                chromaNoise = 0.05f,
                jitter = 1.7f,
                warp = 2.6f,
                dropout = 0.06f,
                ghost = 0.5f,
                ghostDist = 0.013f,
                persist = 0.16f,
                sat = 0.72f,
                hue = 0.06f,
                black = 0.20f,
                whiteClip = 0.93f,
                snow = 0.08f,
                scanline = 0.48f,
                crtBloom = 0.5f,
                crtVignette = 0.36f,
                glare = 0.14f,
                bright = 1.06f,
                // The original home movie's date stamp survived every generation of dubbing.
                osd = OsdStyle.DATE_ONLY,
                osdColor = 0xFFF0E8D8.toInt(),
                tapeSpeed = "LP",
                audio = AudioProfile.LINEAR_EP
            ),

            VhsPreset(
                id = "rental",
                name = "Rental",
                year = "1986",
                format = "VHS · ex-rental, 400 plays",
                blurb = "Be kind, rewind. Shed oxide, creased tape, and a lifetime of other people's VCRs.",
                exposure = 0.99f,
                saturation = 0.94f,
                tintR = 1.03f,
                tintG = 0.99f,
                tintB = 0.94f,
                softness = 0.44f,
                lumaBw = 4.6f,
                chromaBw = 38f,
                chromaDelay = 4.2f,
                sharpen = 0.6f,
                dotCrawl = 0.6f,
                rainbow = 0.34f,
                noise = 0.085f,
                noiseDark = 1.7f,
                chromaNoise = 0.042f,
                jitter = 1.6f,
                warp = 3.0f,
                headSwitch = 1.0f,
                tracking = 0.22f,
                dropout = 0.16f,
                persist = 0.14f,
                sat = 0.74f,
                hue = 0.05f,
                black = 0.17f,
                whiteClip = 0.945f,
                snow = 0.12f,
                curve = 0.05f,
                scanline = 0.52f,
                mask = 0.22f,
                crtBloom = 0.48f,
                crtVignette = 0.4f,
                glare = 0.26f,
                overscan = 0.045f,
                flicker = 0.28f,
                corner = 0.026f,
                osd = OsdStyle.PLAYER,
                osdColor = 0xFFEFEFEF.toInt(),
                tapeSpeed = "SP",
                audio = AudioProfile.WORN
            ),

            VhsPreset(
                id = "security",
                name = "Security",
                year = "1984",
                format = "Time-lapse VCR · 24 hr mode",
                blurb = "Lobby camera on a 24 hour time-lapse deck. Washed out, over-sharpened, always stamped.",
                exposure = 1.05f,
                gamma = 0.94f,
                contrast = 1.22f,
                saturation = 0.35f,
                tintR = 1.0f,
                tintG = 1.02f,
                tintB = 1.0f,
                softness = 0.5f,
                ccdSmear = 0.4f,
                lensBloom = 0.3f,
                lensVignette = 0.42f,
                lumaBw = 4.2f,
                chromaBw = 44f,
                sharpen = 0.9f,
                dotCrawl = 0.35f,
                rainbow = 0.12f,
                noise = 0.095f,
                noiseDark = 2.0f,
                chromaNoise = 0.02f,
                jitter = 1.1f,
                warp = 1.5f,
                headSwitch = 0.9f,
                dropout = 0.07f,
                interlace = 1.0f,
                persist = 0.2f,
                sat = 0.45f,
                black = 0.2f,
                whiteClip = 0.92f,
                snow = 0.06f,
                curve = 0.045f,
                scanline = 0.6f,
                mask = 0.2f,
                crtBloom = 0.3f,
                crtVignette = 0.45f,
                glare = 0.1f,
                overscan = 0.04f,
                bright = 1.05f,
                flicker = 0.25f,
                osd = OsdStyle.SECURITY,
                osdColor = 0xFFFFFFFF.toInt(),
                tapeSpeed = "24H",
                audio = AudioProfile.WORN
            )
        )

        fun byId(id: String): VhsPreset = ALL.firstOrNull { it.id == id } ?: ALL[0]
    }
}
